language: python
python:
- '3.7'
env:
  global:
    secure: QfXgoTOoSf7jj/sIo0Fk/5VsXV4da9Eb4kap9V9fKVjjp0MwRkXX/dh0RQzhP5dKFrzL0u8GXnCU12sX2Hwr8AR/Xqy1XVvFHP2kgpT7qxxczZIyyc2c2AdjBSOylVJC/WUwitdht/aWYIZeW5jBLpFWJ4FvY57RQ+ktQDTuTKPQq5eZ2i3fQMOtynAPVuaQWezxyf+zSuI4zwDzPenBer1DeXE/ZwdnPaczE691KlkxjdnjLn+fAmOUDuiWj85gjzEMbriguVH8z/uCbkt78pgiF5XU6D3tjD+DFRUvNiRKJ7rqTJwVCKCoJyggG2gWWA+ijl6TCO6fUJff63UG+Bxp76Jfj5sLdkKQYcMVNLuQEv0ZlL+rpsm19GdsXHO5hhZVaOkp1bIZXcgusiUr6HB6evex8r40cCq22WUV/hE+RzdkLM63Igubti5FvBTqFQrgt8dk48y8OuQokdmuGpbhtyeDT4zXz9+FoBl8BxyqXGy4JqdEOnlgJlXtNM3cAvpqR0wnK9sxM6/LWOdlTVBCBFqE5zPOm8SihHazugWd6zb8ryQEuESCi9bzCpba4DVhRjopzodc06bBNISuBQjZ5Y/Dv6oi6QKZf63JQYfQ/now6Ct32qVWGNA050Gc2/3elj+G2tGsTg2+kEhCygKenN4hUWFx3E8Vrgp1H2s=
before_install:
- echo $HOME
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda install -y -c anaconda python=3.7.6
- pip install tqdm
- conda config --set always_yes true --set changeps1 no
- conda update -q conda
install:
- conda install -y conda-build
- conda install -y anaconda-client
before_script:
- chmod +x ./deploy_conda.sh
script:
- provider: script
  script: ./deploy_conda.sh
  skip_cleanup: true